// Versão pública de QA/referencias/matriz-conformidade.md. Ao mudar o status de uma cláusula lá,
// atualize aqui também. `criterios` = grupos do harness (QA/scripts/verificar.mjs) que a conferem.
export const CONFORMIDADE = [
  {
    titulo: 'Calculado e verificado',
    status: 'ok',
    descricao: 'A ferramenta calcula e confere contra a norma, com teste automático para cada regra.',
    itens: [
      ['§9.5.2', 'Previsão de carga: iluminação mínima, quantidade e potência de tomadas por cômodo', 'G1'],
      ['§9.5.3', 'Divisão em circuitos; equipamento > 10 A e cozinha/serviço em circuito próprio', 'G3, G13'],
      ['Tabelas 36/37', 'Capacidade de condução, cobre PVC e EPR/XLPE, métodos A1, A2, B1, B2, C e D', 'G2, G8, G17, G21'],
      ['Tabelas 40-42, 45', 'Fatores de temperatura, agrupamento e resistividade do solo', 'G4, G18, G20'],
      ['§6.2.6.1.1 / Tabela 47', 'Seções mínimas: 1,5 mm² iluminação, 2,5 mm² força', 'G4'],
      ['§5.3.4.1', 'Ib ≤ In ≤ Iz e I₂ ≤ 1,45·Iz', 'G4, G24'],
      ['§6.2.7', 'Queda de tensão: 4% no circuito, 5% no total a partir da entrega', 'G5'],
      ['§6.2.6.2', 'Neutro: corrente real por soma vetorial; redução só com as condições declaradas', 'G6, G14'],
      ['Tabela 58', 'Seção do condutor de proteção (PE) em todo circuito', 'G6'],
      ['§5.3.5 / Tabela 30', 'Curto-circuito: I²t ≤ k²S² com a Icc no quadro; capacidade de interrupção', 'G9, G23, G24'],
      ['§5.1.2.2.4', 'Seccionamento automático: TN (Zs·Ia ≤ Uo) e TT (RA·IΔn ≤ UL)', 'G25'],
      ['§5.1.3.2.2 / §6.3.6', 'DR de 30 mA, único ou por grupo, com seletividade do DR a montante', 'G6, G25'],
      ['§6.2.11.1.6 a)', 'Taxa de ocupação do eletroduto', 'G7'],
      ['§6.2.11.1.6 b) / .7', 'Percurso do eletroduto: comprimento entre caixas, curvas e a alternativa da NOTA, nos circuitos e no alimentador (quando cadastrado)', 'G30'],
      ['Tabela 59', 'Espaço de reserva no quadro', 'G24'],
      ['§6.4', 'Equipotencialização principal, PEN ≥ 10 mm², condutor de aterramento (Tabela 52)', 'G24'],
      ['§6.3.5 / Tabelas 31 e 49', 'Especificação do DPS: Up, Uc, In/Iimp e condutor DPS-PE', 'G15, G24'],
      ['§9.1', 'Banheiro: equipotencialização suplementar e DR ≤ 30 mA', 'G22'],
      ['§9.1.2.1 / §9.1.4.3 / §9.1.4.4', 'Volumes do banheiro (0-3) e proibição de dispositivo por volume, quando o chuveiro/banheira e os pontos elétricos são marcados na planta ou em metros', 'G33'],
      ['§9.2 / §9.4', 'Piscina (equipotencialização, DR, SELV nos volumes 0 e 1) e sauna (sem tomadas, IP24, corte a 140 °C)', 'G29'],
      ['§6.1.8.1 / §6.1.5.4', 'Diagrama unifilar e quadro com a numeração dos circuitos; lista de materiais com as cores do §6.1.5.3', 'G28'],
    ],
  },
  {
    titulo: 'Verificado com limite declarado',
    status: 'atencao',
    descricao: 'Coberto em parte. O limite aparece na própria tela, junto do resultado.',
    itens: [
      ['§6.2.6.1.2 c)', 'Curto-circuito em circuito fase-fase: laço entre duas fases, com a Icc informada tomada como a trifásica (a norma não traz a conversão entre tipos de falta)', 'G23'],
      ['§6.3.4.3.2 a)', 'Ia ≤ Ikmin: aprovado só com disparo instantâneo garantido; abaixo disso, depende da curva do fabricante', 'G9, G23'],
      ['§6.3.3.2.6', 'Disparo intempestivo do DR: a fuga normal dos aparelhos não é calculável; há aviso e a opção por grupos', 'G25'],
      ['§6.2.11.1.6', 'Diâmetros de cabo e eletroduto vêm de catálogo (a norma não os tabela): PVC 450/750 V e EPR/XLPE 0,6/1 kV, até 120 mm²', 'G7'],
      ['—', 'Reatância dos condutores: valores de literatura técnica, não da NBR 5410', 'G11'],
      ['§5.3.4.1 / §5.1.2.2.4', 'Instalação existente: seção, disjuntor e PE conferidos; o seccionamento supõe o DR de 30 mA do projeto', 'G28'],
      ['§9.1.2 / §9.1.4 / §9.2.2', 'Sem marcação na planta: volumes do banheiro (e sempre os da piscina) viram lista de conferência manual, sem geometria', 'G22, G29'],
      ['§9.4.4.1.4', 'Sauna: cabo para 170 °C no volume 3 é só avisado — a ferramenta dimensiona PVC e EPR/XLPE', 'G29'],
      ['§6.2.6.2.5', 'Com 3ª harmônica declarada acima de 33%, a ferramenta avisa que o neutro pode precisar ser maior que a fase (Anexo F) em vez de calcular essa seção', 'G34'],
    ],
  },
  {
    titulo: 'Fora da NBR 5410 — informativo',
    status: 'atencao',
    descricao: 'Fonte externa à norma. Nunca substitui o dimensionamento por NBR 5410, que continua somando as cargas cheias.',
    itens: [
      ['—', 'Demanda de iluminação/tomadas pela norma de 9 distribuidoras (opcional). Chuveiro, ar-condicionado e motor ainda não entram nessa conta', 'G32'],
    ],
  },
  {
    titulo: 'Não verificado — e por quê',
    status: 'alerta',
    descricao: 'Fora do alcance da ferramenta. Precisa de projeto e conferência em obra.',
    itens: [
      ['§5.1.2.2.4 (IT)', 'Esquema IT: não se usa em residência', '—'],
      ['—', 'Fator de demanda: a NBR 5410 não tem tabela residencial; é regra de cada distribuidora. A ferramenta soma as cargas', '—'],
      ['Cap. 7', 'Ensaios em obra (continuidade, isolamento, DR): entram como lista de verificação, não como cálculo', '—'],
    ],
  },
]
